name: satellite # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Advanced scalable Open source intelligence platform
description: |
  Satellite is a scalable platform based on LXD, Kubernetes and Juju, to provide
  an easy to use plugin system for automated online reconaissance.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  satellite:
    plugin: dump
    source: git@github.com:alanzanattadev/satellite.git
    organize:
      cli/*: opt/satellite/cli/
      deploy.sh: opt/satellite/deploy.sh
      clean.sh: opt/satellite/clean.sh
      charms/*: opt/satellite/charms/
      config/*: opt/satellite/config/
    stage:
      - opt/satellite
      - usr
    stage-packages:
      - nodejs
      - zip
    override-prime: |
      snapcraftctl prime
      cd opt/satellite/cli
      yarn


apps:
  cli:
    command: env NODE_PATH=$SNAP/opt/satellite/cli/node_modules nodejs $SNAP/opt/satellite/cli/lib/index.js
    plugs:
      - network
      - network-bind
      - home
  deploy:
    command: opt/satellite/deploy.sh
  clean:
    command: opt/satellite/clean.sh
